# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  weight: 1

fr:
  languageCode: fr-fr
  contentDir: content/fr
  weight: 2
  title: Massyle DENDENE
  params:
    description: 'Site personnel de Massyle DENDENE.'
  menu:
    main:
      - name: Biographie
        url: /
        weight: 10
      - name: Exp√©rience
        url: experience/
        weight: 20
      - name: Enseignement
        url: teaching/
        weight: 30
